# Site settings
title: Jeff Ford's Teaching and Research
short-title: jford.org
header-img: "/assets/img/Gustavus-Adolphus-2.jpg"
email: jford@gustavus.edu
description: "Visiting instructor in the Mathematics, Computer Science, and Statistics department at Gustavus Adolphus College"
baseurl: ""
url: "https://jford.org"
#twitter_username: StevenXClontz
github_username:  jford1906
booking_link: "https://jeffford.youcanbook.me"
#facebook_username:
navbar-links:
  - title: About
    url:   /about/
  - title: Classes
    url:   /classes/
  - title: Resources
    url:  /resources/
  - title: Research
    url:   /research/

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /blog/:categories/:year/:month/:day/:title/
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
gems: [jekyll-paginate]
